version: '3.8'

services:
  livetrans:
    image: node:20
    container_name: livetrans
    restart: always
    working_dir: /app
    volumes:
      - ./.output:/app
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - NITRO_PORT=8081
      - NUXT_OPENAI_API_KEY=${OPENAI_API_KEY}
      - NUXT_OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - NUXT_OPENAI_MODEL=${OPENAI_MODEL}
    command: node server/index.mjs